### ISSUE TITLE
Ps3/Vita still not being picked up after 3.2.0

### ISSUE THREAD

**Issue by deejbruce** [Tustin/PlayStationDiscord#119]
In the last update, They were being picked up but I kept having an error "There was a communication error with Discord" But I could at least see the game, Now it just says I'm offline and I've tried logging out and in again and nothing, I'm defitinally online though.

**Comment by Tustin** [comment]
I think the new Sony API I use got rid of PS3/Vita status. I'll have to test it out to make sure but that's most likely the reason why. I'll have to come up with a fix for it

**Comment by deejbruce** [comment]
Ah, Figured it was bound to happen eventually after they turned off the ability to send messages from ps3 to ps4 so I wouldn't be surprised.

**Comment by deejbruce** [comment]
![3SexhynRyg](https://user-images.githubusercontent.com/7811248/99910878-74e2fd80-2ce8-11eb-82f4-38846b86149d.png)
Like I did check with 3.1.1 and It was able to pick it up, It just wouldn't connect to Discord.

**Comment by Tustin** [comment]
> ![3SexhynRyg](https://user-images.githubusercontent.com/7811248/99910878-74e2fd80-2ce8-11eb-82f4-38846b86149d.png)
> 
> Like I did check with 3.1.1 and It was able to pick it up, It just wouldn't connect to Discord.

Yeah it would pick it up but never send to Discord because the old Discord client ID for PS3 and Vita were invalid

**Comment by doggonator** [comment]
Is this the end of dicord status for PS3 games then?

**Comment by PabloGirol** [comment]
The old api still works tho, should be a workaround to make it work

**Comment by Tustin** [comment]
> The old api still works tho, should be a workaround to make it work

It does, I'm just not sure if PS5 titles show up on there (which I want to support more than I do PS3/Vita). If they do, I can just go back to the old API for now.

**Comment by PabloGirol** [comment]
Using both APIs (New and Old ones) in the app and use one of them just for psvita and ps3 and the other to Ps4 and Ps5 Should work till the older API dies, then well... there is no way to make it work right now

**Comment by Jump-Suit** [comment]
I'd prefer my ps3 and vita games being displayed than PS4 and PS5 personally. PS5 is still fresh and filled with OS bugs, it is a shame to see changes to the API break PS3 and Vita support as that is what I use more. I'd have to somehow source another Discord Rich Presence to PlayStation alternative IF one even exists...

**Comment by doggonator** [comment]
> 
> 
> I'd prefer my ps3 and vita games being displayed than PS4 and PS5 personally. PS5 is still fresh and filled with OS bugs, it is a shame to see changes to the API break PS3 and Vita support as that is what I use more. I'd have to somehow source another Discord Rich Presence to PlayStation alternative IF one even exists...

Yeah I was only using for the PS3 discord presence, but worst case senario I can play most of my PS3 games through RPCS3 now and get Rich Presence that way. But it would still be nice to have it working again.

**Comment by xetsubou** [comment]
> Using both APIs (New and Old ones) in the app and use one of them just for psvita and ps3 and the other to Ps4 and Ps5 Should work till the older API dies, then well... there is no way to make it work right now, Right?

Yeah could you just use both API? Maybe make 2 apps if necessary

**Comment by hanarix** [comment]
I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 Discord app id with the new one and it works, but I don't have the other consoles to test them.
![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)

**Comment by miloehx** [comment]
> 
> 
> I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)

where can i find the new ps3 client id

**Comment by deejbruce** [comment]
I don't think this is going to get fixed is it?

**Comment by LieutenantSugar** [comment]
> 
> 
> I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)

How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.

**Comment by hanarix** [comment]
> > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> 
> How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.

I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.

**Comment by Deltara3** [comment]
> > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > 
> > 
> > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> 
> I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.

This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml or a file along those lines in the resources folder. Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!

**Comment by LieutenantSugar** [comment]
> 
> 
> > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > 
> > > 
> > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > 
> > 
> > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> 
> This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!

Aww hell yeah! The other method didn't work for me either but this one sure did! I really do hope this issue gets fixed in the next update so people don't have to do all this to make it work. Thanks for your comment, bud! Really glad the PS3 shows a presence now! :D

**Comment by Deltara3** [comment]
> > > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > > 
> > > > 
> > > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > > 
> > > 
> > > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> > 
> > 
> > This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!
> 
> Aww hell yeah! The other method didn't work for me either but this one sure did! I really do hope this issue gets fixed in the next update so people don't have to do all this to make it work. Thanks for your comment, bud! Really glad the PS3 shows a presence now! :D I'm a bit bummed that the images for the games don't show, but a working presence is better than nothing!

No problem, it is sad that the images don't show, but I was used to it with the PS3 python/javascript presence, only issue with those two was that it required CFW and webmanMOD. Which not everybody has access to or wants to have. Glad to know that I helped someone! To be honest, I thought the instructions might have been too convoluted.

**Comment by Naddly** [comment]
> 
> 
> > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > 
> > > 
> > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > 
> > 
> > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> 
> This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!

It dodn't work for me, the app display the game normally but nothing happens on my discord :/

**Comment by Deltara3** [comment]
> > > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > > 
> > > > 
> > > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > > 
> > > 
> > > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> > 
> > 
> > This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!
> 
> It didn't work for me, the app displays the game normally but nothing happens on my discord :/

Which build of PlayStationDiscord are you using? I chose 3.1.2 rather than 3.1.1 because I had sign in issues with 3.1.1. I did make a repo for the patch. Which can be found [here](https://github.com/Deltara3/PlayStationDiscordPatch).

**Comment by Naddly** [comment]
> 
> 
> > > > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > > > 
> > > > > 
> > > > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > > > 
> > > > 
> > > > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> > > 
> > > 
> > > This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!
> > 
> > 
> > It didn't work for me, the app displays the game normally but nothing happens on my discord :/
> 
> Which build of PlayStationDiscord are you using? I chose 3.1.2 rather than 3.1.1 because I had sign in issues with 3.1.1. I did make a repo for the patch. Which can be found [here](https://github.com/Deltara3/PlayStationDiscordPatch). In the releases there is a prebuilt app.asar package for 3.1.2. If that still doesn't work, check to see if you have game activity turned off in Discord.

Yep, it still doesn't work. Discord game activity is on and I'm using PlayStationDiscord 3.1.2 with your patch. I've tried 3.1.1 but had same issue than you

**Comment by Naddly** [comment]
Wait, it now just worked XD
Thank you for the help!

**Comment by Deltara3** [comment]
> Wait, it now just worked XD
> Thank you for the help!

Oh, ok that's good, I wonder what happened. No problem.

**Comment by Naddly** [comment]
> 
> 
> > Wait, it now just worked XD
> > Thank you for the help!
> 
> Oh, ok that's good, I wonder what happened. No problem.

Idk, I just tried to open it one last time and it worked

**Comment by Jump-Suit** [comment]
Simple installation worked for me @Deltara3 your amazing thank you very much!

**Comment by deejbruce** [comment]
Can confirm, @Deltara3 The fix worked for me too.

**Comment by Deltara3** [comment]
Nice, @Jump-Suit and @deejbruce, haven't been online for a bit, so I just saw it now, no problem though.

**Comment by Amieew0** [comment]
Is there a way to add the icons? i'm sorry for my bad English, i'm Argentina. Thanks Deltara3. 
it worked!

**Comment by Deltara3** [comment]
> Is there a way to add the icons? i'm sorry for my bad English, i'm Argentina. Thanks Deltara3.
> it worked!

No problem, but I'm sure the icons sadly can't be added, due to limitations of the older version.

**Comment by PabloGirol** [comment]
Any official updates about this?, will the ps3/vita support be dropped?

**Comment by Alexis1887** [comment]
> > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > 
> > > 
> > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > 
> > 
> > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> 
> This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!

I just tried to do this and even though it successfully worked, like im showing up online now, this error message pops up every time. I tried it again but it still did this. Idk if i did something wrong twice
![image](https://user-images.githubusercontent.com/80853327/111527955-32e33900-8769-11eb-9edf-3b2fbb8f0b76.png)

**Comment by Deltara3** [comment]
> > > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > > 
> > > > 
> > > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > > 
> > > 
> > > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> > 
> > This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!
> 
> I just tried to do this and even though it successfully worked, like im showing up online now, this error message pops up every time. I tried it again but it still did this. Idk if i did something wrong twice (I'm not great at coding)
> 
> Here's the log: 
> [2021-03-17 21:30:07.914] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
>     at Timeout.setTimeout (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:99:47)
>     at ontimeout (timers.js:425:11)
>     at tryOnTimeout (timers.js:289:5)
>     at unrefdHandle (timers.js:509:7)
>     at Timer.processTimers (timers.js:211:12)
> [2021-03-17 21:30:12.009] [warn] DiscordController disconnected
> 
> 
> ![image](https://user-images.githubusercontent.com/80853327/111527955-32e33900-8769-11eb-9edf-3b2fbb8f0b76.png)
> 

To me that looks like something to do with Discord or possibly the application id's or incorrect. I made a repository with the patch already done. You just have to replace the asar file after downloading. I would try that, if that doesn't work it's got to be something with Discord.

**Comment by Alexis1887** [comment]
> > > > > > I found a workaround for this. I used the 3.1.1 code and replaced the old PS3 client id with the new one and it works, but I don't have the other consoles to test them.
> > > > > > ![image](https://user-images.githubusercontent.com/66530334/100313239-ee9e1400-2f92-11eb-91fb-9417682ea5f8.png)
> > > > > 
> > > > > 
> > > > > How did you go about doing this? I'm tempted to do this myself until this issue is properly fixed.
> > > > 
> > > > 
> > > > I downloaded the 3.1.1 code from [here](https://github.com/Tustin/PlayStationDiscord/tree/v3.1.1) and replaced the old PS3 ID with the new one from [this](https://github.com/Tustin/PlayStationDiscord/commit/746884a84e45d3d14a222dc9ca16f82fd4cdbf6f) commit on the PlayStation3.ts file. Ran **npm install** and **npm run start** on PowerShell and it works.
> > > 
> > > 
> > > This didn't work for me. But I found a different solution. What worked was this. Uninstalled the current PlayStationDiscord program and installed 3.1.2. Opened File Explorer and navigated to C:\Program Files\PlayStationDiscord\resources. Deleted app-update.yml in the resources folder (this is to prevent PlayStationDiscord from updating). Copied the app.asar to my Desktop (any path is fine). Opened Command Prompt and used the cd command to navigate to my Desktop (or the path you chose). I then ran npx asar extract app.asar extracted. Navigate to the extracted folder and inside that folder navigate to Consoles. Open PlayStation3.js and/or PlayStationVita in a text editor. Look for a long string of numbers. Replace just those numbers for both consoles. PlayStation 3: 772576154267549717, PlayStation Vita: 772576212782546975. After that, save the files and proceed. If you closed Command Prompt, open it again and navigate to the directory you extracted the files at. Make sure not to enter the extracted files directory. Delete the previous app.asar file. Then run npx asar pack extracted app.asar. After that replace the app.asar file in C:\Program Files\PlayStationDiscord\resources and you're done!
> > 
> > 
> > I just tried to do this and even though it successfully worked, like im showing up online now, this error message pops up every time. I tried it again but it still did this. Idk if i did something wrong twice (I'm not great at coding)
> > Here's the log:
> > [2021-03-17 21:30:07.914] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
> > at Timeout.setTimeout (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:99:47)
> > at ontimeout (timers.js:425:11)
> > at tryOnTimeout (timers.js:289:5)
> > at unrefdHandle (timers.js:509:7)
> > at Timer.processTimers (timers.js:211:12)
> > [2021-03-17 21:30:12.009] [warn] DiscordController disconnected
> > ![image](https://user-images.githubusercontent.com/80853327/111527955-32e33900-8769-11eb-9edf-3b2fbb8f0b76.png)
> 
> To me that looks like something to do with Discord or possibly the application id's are incorrect. I made a repository with the patch already done. You just have to replace the asar file after downloading the patched one. I would try that, if that doesn't work it's got to be something with Discord.

Worked perfectly, tysm for the help. I guess the problem was the .asar file.
